### ISSUE TITLE
麻烦抄的时候修改下简介，手动艾特作者要感谢的，你还把人作者开源协议给删了，你是真恶心啊

### ISSUE THREAD

**Issue by limuen** [yijunsong-budidiao/Joy-Admin#3]

**Comment by yijunsong-budidiao** [comment]
你这种人才是真的恶心，首先我已经加过作者微信了，已经问过作者了，这个项目随便使用，作者的开源协议你读过没有。要不要我把微信聊天截图发给你呀。而且这个项目我只是套用作者的管理系统壳子而已，里面其他后续功能高德地图，canvas，编辑器等功能都是我独立开发的，你可以去作者的项目对比一下好吗。我从来没有说过这个项目是我从0开发的，最近工作比较忙，没时间维护，qq群早都没人说话，你发也没用，我已经解散。我还有微信群你要不要加一下啊，我可以发你二维码。还有你说的艾特作者，作者根本不在意这个东西。为了防止你这种狗继续出现，现在项目最后已经加上作者链接了。我不知道你是哪条狗，来我这里狗叫什么东西，自己没有搞清楚事实就开始喷人，如果你是作者告诉我不可以使用，我直接可以把项目下掉，可惜你不是，你算个什么东西啊。


| |
yijunsong666
|
|
***@***.***
|
签名由网易邮箱大师定制
在2022年8月5日 ***@***.***> 写道：
